import {createServer } from 'miragejs';
import batman1 from './assets/Images/batman.jpg';
import batman2 from './assets/Images/batman1.jpg';
import inception from './assets/Images/inception.jpg';
import inception1 from './assets/Images/inception1.webp';
import socialnetwork from './assets/Images/socialnetwork.webp';
import socialnetwork1 from './assets/Images/socialnetwork1.webp';
import avengers from './assets/Images/theavengers.webp';
import avengers1 from './assets/Images/theavengers1.jpg';
import wolf from './assets/Images/wolf1.webp';
import wolf1 from './assets/Images/wolf2.jpg';
import fightclub from './assets/Images/fightclub.webp';
import fightclub1 from './assets/Images/fightclub1.jpg';
import forrestgump from './assets/Images/forrestgump2.webp';
import forrestgump1 from './assets/Images/forrestgump1.webp';
import blackpanther from './assets/Images/blackpanther.webp';
import blackpanther1 from './assets/Images/blackpanther1.webp';
import gravity from './assets/Images/gravity.webp';
import gravity1 from './assets/Images/gravity1.jpg';
import intersteller from './assets/Images/intersteller.webp';
import intersteller1 from './assets/Images/intersteller1.webp';
import breakingbad from './assets/Images/breakingbad.webp';
import breakingbad1 from './assets/Images/breakingbad1.webp';
import got from './assets/Images/got.webp';
import got1 from './assets/Images/got1.webp';
import sherlock from './assets/Images/sherlock.webp';
import sherlock1 from './assets/Images/sherlock1.jpg';
import friends from './assets/Images/friends.webp';
import friends1 from './assets/Images/friends1.webp';
import narcos from './assets/Images/narcos.webp';
import narcos1 from './assets/Images/narcos1.webp';
import blackmirror from './assets/Images/blackmirror.webp';
import blackmirror1 from './assets/Images/blackmirror1.webp';
import dark from './assets/Images/dark.webp';
import dark1 from './assets/Images/dark1.jpg';
import boys from './assets/Images/boys.webp';
import boys1 from './assets/Images/boys1.jpg';
import strangerthings from './assets/Images/strangerthings.webp';
import strangerthings1 from './assets/Images/strangerthings1.jpg';
import walkingdead from './assets/Images/walkingdead.webp';
import walkingdead1 from './assets/Images/walkingdead1.jpg';
import dunemain from './assets/Images/dune-main.webp';
import dunebanner from './assets/Images/dune-banner.jpg';
import spidermain from './assets/Images/spiderman-main.jpg';
import spiderbanner from './assets/Images/spiderman-banner.jpg';
import breathemain from './assets/Images/breathe-main.webp';
import breathebanner from './assets/Images/breathe-banner.jpg';
import familymanmain from './assets/Images/familyman-main.webp';
import familymanbanner from './assets/Images/familyman-banner.webp';
import despicablememain from './assets/Images/despicableme-main.webp';
import despicablemebanner from './assets/Images/despicableme-banner.webp';
import badboysmain from './assets/Images/avengers-main.webp';
import badboysbanner from './assets/Images/avengers-banner.webp';
import birdsmain from './assets/Images/birdsmain.webp';
import birdsbanner from './assets/Images/birdsbanner.jpg';
import topgunmain from './assets/Images/topgun-main.webp';
import topgunbanner from './assets/Images/topgun-banner.jpg';
import shangchimain from './assets/Images/shangchi-mein.webp';
import shangchibanner from './assets/Images/shangchi-banner.jpg';
import creedmain from './assets/Images/creed-main.webp';
import creedbanner from './assets/Images/creed-banner.webp';
import martianmain from './assets/Images/martian-main.webp';
import martianbanner from './assets/Images/martian-banner.jpg';
import junglebookmain from './assets/Images/junglebookmain.webp';
import junglebookbanner from './assets/Images/junglebookbanner.jpg';
import mandalorianmain from './assets/Images/mando-main.webp';
import mandalorianbanner from './assets/Images/mando-banner.webp';
import thirteenmain from './assets/Images/13reasons-main.webp';
import thirteenbanner from './assets/Images/13reasons-banner.jpg';
import jackryanmain from './assets/Images/jackryan-main.webp';
import jackryanbanner from './assets/Images/jackryan-banner.jpg';
import madmaxmain from './assets/Images/madmax-main.webp';
import madmaxbanner from './assets/Images/madmax-banner.jpg';
import transformermain from './assets/Images/transformer-main.webp';
import transformerbanner from './assets/Images/transformer-banner.jpg';
import avengersmain from './assets/Images/avengers-main.webp';
import avengersbanner from './assets/Images/avengers-banner.webp';
import parasitemain from './assets/Images/parasite-main.webp';
import parasitebanner from './assets/Images/parasite-banner.webp';
import arrivalmain from './assets/Images/arrival-main.webp';
import arrivalbanner from './assets/Images/arrival-banner.jpg';
import blademain from './assets/Images/blade-main.webp';
import bladebanner from './assets/Images/blade-banner.webp';
import mirzapurmain from './assets/Images/mirzapur-main.webp';
import mirzapurbanner from './assets/Images/mirzapur-banner.webp';
import scaredmain from './assets/Images/scared-main.webp';
import scaredbanner from './assets/Images/scared-banner.jpg';
import asurmain from './assets/Images/asur-main.webp';
import asurbanner from './assets/Images/asur-banner.webp';
import Lvdmain from './assets/Images/lvd-main.webp';
import Lvdbanner from './assets/Images/lvd-banner.webp';
import lucifermain from './assets/Images/lucifer-main.webp';
import luciferbanner from './assets/Images/lucifer-banner.webp';
import delhimain from './assets/Images/delhicrime-main.webp';
import delhibanner from './assets/Images/delhicrime-banner.webp';
import blacksummermain from './assets/Images/blacksummer-main.webp';
import blacksummerbanner from './assets/Images/blacksummer-banner.webp';
import sweetmain from './assets/Images/sweethome-main.webp';
import sweetbanner from './assets/Images/sweethome-banner.webp';
import Bloodhoundsmain from './assets/Images/bloodhounds-main.webp';
import Bloodhoundsbanner from './assets/Images/bloodhounds-banner.jpg';
import hellboundmain from './assets/Images/hellbound-main.webp';
import hellboundbanner from './assets/Images/hellbound-banner.webp';
import Allmain from './assets/Images/all-main.webp';
import Allbanner from './assets/Images/all-banner.webp';

createServer({
    routes() {
      this.namespace = 'api';

      this.get("/movies", () => ({
        movies: [
          {
            id: 1,
            mainImage: batman1,
            bannerImage: batman2,
            title: "The Dark Knight",
            Description: "Christopher Nolan's superhero thriller starring Christian Bale as Batman and Heath Ledger as the Joker is widely regarded as one of the greatest superhero movies of all time.",
            Director: "Christopher Nolan",
            duration: '2h 32min',
            video: "https://www.youtube.com/watch?v=_PZpmTj1Q8Q",
            year: "2008",
            rated: "PG-13",
            rating: 7,
            imdb: '9.0',
            rottenTomatoesRating: '94%',
            type: "movie",
            actors: ["Christen Bale", "Heath Ledger"]
          },
          {
            id: 2,
            mainImage: inception,
            bannerImage: inception1,
            title: "Inception",
            Description: "Christopher Nolan's mind-bending sci-fi action film starring Leonardo DiCaprio, Joseph Gordon-Levitt, and Ellen Page is a masterclass in storytelling and visuals.",
            Director: "Christopher Nolan",
            duration: '2h 22min',
            video: "https://www.youtube.com/watch?v=FiM51gvvW_s",
            year: "2010",
            rated: "PG-13",
            rating: 7,
            imdb: '8.8',
            rottenTomatoesRating: '91%',
            type: "movie",
            actors: ["Leonardo DiCaprio", "Ellen Page"]
          },
          {
            id: 3,
            mainImage: socialnetwork,
            bannerImage: socialnetwork1,
            title: "The Social Network",
            Description: "David Fincher's biographical drama about the founding of Facebook, starring Jesse Eisenberg as Mark Zuckerberg, is a thought-provoking exploration of ambition and friendship.",
            Director: "David Fincher",
            duration: '2h 0min',
            video: "https://www.youtube.com/watch?v=lB95KLmpLR4",
            year: "2010",
            rated: "PG-13",
            rating: 6,
            imdb: '7.8',
            rottenTomatoesRating: '96%',
            type: "movie",
            actors: ["Jesse Eisenberg", "Andrew Garfield"]
          },
          {
            id: 4,
            mainImage: avengers,
            bannerImage: avengers1,
            title: "The Avengers",
            Description: "Joss Whedon's superhero blockbuster brought together some of Marvel's most iconic characters, including Iron Man, Captain America, Thor, and the Hulk, in a thrilling adventure.",
            Director: "Joss Whedon",
            duration: '2h 23min',
            video: "https://www.youtube.com/watch?v=eOrNdBpGMv8",
            year: "2010",
            rated: "R13",
            rating: 5,
            imdb: '8.0',
            rottenTomatoesRating: '91%',
            type: "movie",
            actors: ["Tom Hanks", "Steven Spielberg"]
          },
          {
            id: 5,
            mainImage: wolf,
            bannerImage: wolf1,
            title: "The Wolf of Wall Street",
            Description: "Martin Scorsese's biographical comedy-drama, starring Leonardo DiCaprio as stockbroker Jordan Belfort, is a wild and entertaining ride through the world of finance and excess.",
            Director: "Martin Scorsese",
            duration: '3h 0min',
            video: "https://www.youtube.com/watch?v=iszwuX1AK6A",
            year: "2013",
            rated: "R",
            rating: 8,
            imdb: '8.2',
            rottenTomatoesRating: '80%',
            type: "movie",
            actors: ["Leonardo DiCaprio", "Jonah Hill"]
          },
          {
            id: 6,
            mainImage: fightclub,
            bannerImage: fightclub1,
            title: "Fight Club",
            Description: "Pitt makes multiple appearances on this list, including in this R-rated movie also starring Edward Norton about an underground fight club.",
            Director: "David Fincher",
            duration: '2h 9min',
            video: "https://www.youtube.com/watch?v=BdJKm16Co6M&t=33s",
            year: "1999",
            rated: "R",
            rating: 7,
            imdb: '8.8',
            rottenTomatoesRating: '80%',
            type: "movie",
            actors: ["Brad Pitt", "Ed Norton"]
          },
          {
            id: 7,
            mainImage: forrestgump,
            bannerImage: forrestgump1,
            title: "Forrest Gump",
            Description: "Hanks, who’d already become an 80s movie icon, won his second consecutive Best Actor Oscar for Forrest Gump, playing the slow but kind and loyal Forrest as he bumps in and out of some of the biggest moments in 20th century history while pining for troubled childhood friend Jenny (Robin Wright).",
            Director: "Robert Zemeckis",
            duration: '2h 22min',
            video: "https://www.youtube.com/watch?v=bLvqoHBptjg",
            year: "1994",
            rated: "R13",
            rating: 4,
            imdb: '8.8',
            rottenTomatoesRating: '76%',
            type: "movie",
            actors: ["Tom Hanks", " Robin Wright"]
          },
          {
            id: 8,
            mainImage: blackpanther,
            bannerImage: blackpanther1,
            title: "Black Panther",
            Description: "Ryan Coogler's superhero film, set in the Marvel Cinematic Universe, is a groundbreaking and culturally significant exploration of identity, community, and power.",
            Director: 'Ryan Coogler',
            duration: '2h 15min',
            video: "https://www.youtube.com/watch?v=xjDjIWPwcPU",
            year: "2018", 
            rated: "PG-13",
            rating: 9,
            imdb: '7.3',
            rottenTomatoesRating: '96%',
            type: "movie",
            actors: ["Chadwick Boseman" ,"Micheah B Jordan" ]
          },
          {
            id: 9,
            mainImage: gravity,
            bannerImage: gravity1,
            title: "Gravity",
            Description: " Directed by Alfonso Cuarón. With Sandra Bullock, George Clooney, Ed Harris, Orto Ignatiussen. Dr Ryan Stone, an engineer on her first time on a space mission, and Matt Kowalski, an astronaut on his final expedition, have to survive in space after they are hit by debris while spacewalking.",
            Director: "Alfonso Cuarón",
            duration: '1h 31min',
            video: "https://www.youtube.com/watch?v=OiTiKOy59o4",
            year: "2013",
            rated: "PG-13",
            rating: 7,
            imdb: '7.7',
            rottenTomatoesRating: '96%',
            type: "movie",
            actors: ["Sandra Bullock", "George Clooney"]
          },
          {
            id: 10,
            mainImage: intersteller,
            bannerImage: intersteller1,
            title: "Interstellar",
            Description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
            Director: "Christopher Nolan",
            duration: '2h 49min',
            video: "https://www.youtube.com/watch?v=2LqzF5WauAw",
            year: "2014",
            rated: "PG-13",
            rating: 10,
            imdb: '8.7',
            rottenTomatoesRating: '73%',
            type: "movie",
            actors: ["Mathew McConaughey", "Anne Hathway"]
          },
          {
            id: 11,
            mainImage: breakingbad,
            bannerImage: breakingbad1,
            title: "Breaking Bad",
            Description: "Breaking Bad is an American crime drama television series created and produced by Vince Gilligan. Set and filmed in Albuquerque, New Mexico, the series follows Walter White, an underpaid, overqualified, and dispirited high-school chemistry teacher who is struggling with a recent diagnosis of stage-three lung cancer.",
            Director: "Vince Gilligan",
            duration: '5 Seasons 62 Episodes',
            video: "https://www.youtube.com/watch?v=HhesaQXLuRY",
            year: "2008-2013",
            rated: "TV-MA",
            rating: 7,
            imdb: '9.5',
            rottenTomatoesRating: '96%',
            type: "tvseries",
            actors: ["Bryan Cranston", "Aaron Paul"]
          },
          {
            id: 12,
            mainImage: got,
            bannerImage: got1,
            title: "Game Of Thrones",
            Description: "Game of thrones s an adaptation of A Song of Ice and Fire, a series of fantasy novels by George R. R. Martin, the first of which is A Game of Thrones.",
            Director: "Mark Mylod",
            duration: '8 Seasons 73 Episodes',
            video: "https://www.youtube.com/watch?v=KPLWWIOCOOQ",
            year: " 2010 to 2019",
            rated: "R",
            rating: 5,
            imdb: '9.2',
            rottenTomatoesRating: '89%',
            type: "tvseries",
            actors: ["Peter Dinklage", "Emilia Clark"]
          },
          {
            id: 13,
            mainImage: sherlock,
            bannerImage: sherlock1,
            title: "Sherlock",
            Description: "Sherlock is a British mystery crime drama television series based on Sir Arthur Conan Doyle’s Sherlock Holmes detective stories. Created by Steven Moffat and Mark Gatiss.",
            Director: "Paul McGuigan",
            duration: '4 Seasons 12 Episodes',
            video: "https://www.youtube.com/watch?v=gGqWqGOSTGQ",
            year: "2010-2016",
            rated: "TV-14",
            rating: 4,
            imdb: '9.1',
            rottenTomatoesRating: '78%',
            type: "tvseries",
            actors: ["Benedict Cumberbatch" , "Martin Freeman"]
          },
          {
            id: 14,
            mainImage: friends,
            bannerImage: friends1,
            title: "Friends",
            Description: "Friends is an American television sitcom created by David Crane and Marta Kauffman. The show revolves around six friends in their 20s and 30s who live in Manhattan, New York City.",
            Director: "David Crane",
            duration: '10 Seasons 236 Episodes',
            video: "https://www.youtube.com/watch?v=HLQNDVG-K9g",
            year: "1994-2004",
            rated: "TV-14",
            rating: 6,
            imdb: '8.9',
            rottenTomatoesRating: '78%',
            type: "tvseries",
            actors: ["Matt Le Blanc", "Jennifer Aniston"]
          },
          {
            id: 15,
            mainImage: narcos,
            bannerImage: narcos1,
            title: "Narcos",
            Description: "Narcos is an American-Colombian crime drama television series created and produced by Chris Brancato, Carlo Bernard, and Doug Miro. Set and filmed in Colombia.",
            Director: "José Padilha",
            duration: '3 Seasons 30 Episodes',
            video: "https://www.youtube.com/watch?v=RNWAKZzgbp4",
            year: "2015-2017",
            rated: "TV-MA",
            rating: 7,
            imdb: '8.8',
            rottenTomatoesRating: '89%',
            type: "tvseries",
            actors: ["Pedro Pascal", "Arturo Castro"]
          },
          {
            id: 16,
            mainImage: blackmirror,
            bannerImage: blackmirror1,
            title: "Black Mirror",
            Description: "Black Mirror is a British anthology television series created by Charlie Brooker. Individual episodes explore a diversity of genres, but most are set in near-future dystopias with science fiction technology, a type of speculative fiction.",
            Director: "Charlie Brooker",
            duration: '7 Seasons 33 Episodes',
            video: "https://www.youtube.com/watch?v=5jY1ecibLYo",
            year: "2011-2023",
            rated: "TV-MA",
            rating: 6,
            imdb: '8.7',
            rottenTomatoesRating: '83%',
            type: "tvseries",
            actors: ["Wunmi Mosaku", "Monica Dolan"]
          },
          {
            id: 17,
            mainImage: dark,
            bannerImage: dark1,
            title: "Dark",
            Description: "Dark is a German science fiction thriller television series co-created by Baran bo Odar and Jantje Friese. It ran for three seasons from 2017 to 2020. The story follows characters from the fictional village of Winden, Germany, as they pursue the truth in the aftermath of a child’s disappearance.",
            Director: "Baran bo Odar",
            duration: '3 Seasons 26 Episodes',
            video: "https://www.youtube.com/watch?v=cq2iTHoLrt0", 
            year: "2017-2020",
            rated: "TV-MA",
            rating: 8,
            imdb: '8.7',
            rottenTomatoesRating: '95%',
            type: "tvseries",
            actors: ["Louis Hoffman", "Lisa Vicari"]
          },
          {
            id: 18,
            mainImage: boys,
            bannerImage: boys1,
            title: "The Boys",
            Description: "The Boys is an American superhero television series developed by Eric Kripke for Amazon Prime Video. Based on the comic book of the same name by Garth Ennis and Darick Robertson, it follows the eponymous team of vigilantes as they combat super powered individuals who abuse their abilities.",
            Director: "Eric Kripke",
            duration: '4 Seasons 32 Episodes',
            video: "https://www.youtube.com/watch?v=EzFXDvC-EwM",
            year: "2019-2024",
            rated: "TV-MA",
            rating: 10,
            imdb: '8.7',
            rottenTomatoesRating: '93%',
            type: "tvseries",
            actors: ["Anthory Starr", "Karl Urban"]
          },
          {
            id: 19,
            mainImage: strangerthings,
            bannerImage: strangerthings1,
            title: "Stranger Things",
            Description: "Stranger Things is an American science fiction horror drama television series created by the Duffer Brothers, who also serve as showrunners and are executive producers along with Shawn Levy and Dan Cohen.",
            Director: "The Duffer Brothers",
            duration: '4 Seasons 34 Episodes',
            video: "https://www.youtube.com/watch?v=mVsJXiI60a0",
            year: "2016-2025",
            rated: "TV-MA",
            rating: 9,
            imdb: '8.7',
            rottenTomatoesRating: '91%',
            type: "tvseries",
            actors: ["Millie Bobby Brown", "Finn Wolfhard"]
          },
          {
            id: 20,
            mainImage: walkingdead,
            bannerImage: walkingdead1,
            title: "The Walking Dead",
            Description: "The Walking Dead is an American post-apocalyptic horror television series based on the comic book series. The series features a large ensemble cast as survivors of a zombie apocalypse trying to stay alive under near-constant threat of attacks from zombies known as “walkers”.",
            Director: "Frank Darabont",
            duration: '11 Seasons 177 Episodes',
            video: "https://www.youtube.com/watch?v=iTOaFootkSk",
            year: "2010-2022",
            rated: "TV-MA",
            rating: 6,
            imdb: '8.1',
            rottenTomatoesRating: '79%',
            type: "tvseries",
            actors: ["Norman Reedus", "Melissa McBride"],
          },
          {
            id: 21,
            mainImage: dunemain,
            bannerImage: dunebanner,
            title: "Dune",
            Description: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
            Director: "Denis Villeneuve",
            duration: '2h 35min',
            video: "https://www.youtube.com/watch?v=n9xhJrPXop4",
            year: "2021",
            rated: "PG-13",
            rating: 9,
            imdb: '8.0',
            rottenTomatoesRating: '83%',
            type: "movie",
            actors: ['Timothee Chalamet', 'Rebecca Ferguson'],
          },
          {
            id: 22,
            mainImage: spidermain,
            bannerImage: spiderbanner,
            title: "Spider-Man: No Way Home",
            Description: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
            Director: "Jon Watts",
            duration: '2h 28min',
            video: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
            year: "2021",
            rated: "PG-13",
            rating: 7,
            imdb: '8.2',
            rottenTomatoesRating: '93%',
            type: "movie",
            actors: ['Tom Holland', 'Zendaya', 'Benedict Cumberbatch'],
          },
          {
            id: 23,
            mainImage: breathemain,
            bannerImage: breathebanner,
            title: "Breathe: Into The Shadows",
            Description: "'A father's love can save a life... or take one,' sets the tone for a dark and gritty series",
            Director: "Mayank Sharma",
            duration: '2 Seasons 16 Episodes',
            video: "https://www.youtube.com/watch?v=nxE-k2MLQIA",
            year: "2020",
            rated: "TV-14",
            rating: 7,
            imdb: '7.6',
            rottenTomatoesRating: '76%',
            type: "tvseries",
            actors: ['Abhishek Bachchan', 'Amit Sadh'],
          },
          {
            id: 24,
            mainImage: familymanmain,
            bannerImage: familymanbanner,
            title: "The Family Man",
            Description: "A working man from the National Investigation Agency tries to protect the nation from terrorism, but he also needs to keep his family safe from his secret job.",
            Director: "Krishna DK",
            duration: '2 Seasons 20 Episodes',
            video: "https://www.youtube.com/watch?v=XatRGut65VI",
            year: "2019-2021",
            rated: "TV-MA",
            rating: 6,
            imdb: '8.7',
            rottenTomatoesRating: '87%',
            type: "tvseries",
            actors: ['Manoj Bajpayee','Samantha Ruth Prabhu'],
          },
          {
            id: 25,
            mainImage: despicablememain,
            bannerImage: despicablemebanner,
            title: "Desipcable Me",
            Description: "Gru, a criminal mastermind, adopts three orphans as pawns to carry out the biggest heist in history. His life takes an unexpected turn when the little girls see the evildoer as their potential father.",
            Director: "Pierre Coffin",
            duration: '1h 35min',
            video: "https://www.youtube.com/watch?v=zzCZ1W_CUoI",
            year: "2010",
            rated: "PG",
            rating: 6,
            imdb: '7.6',
            rottenTomatoesRating: '80%',
            type: "movie",
            actors: ['Steve Caroll', 'Jason Segel'],
          },
          {
            id: 26,
            mainImage: badboysmain,
            bannerImage: badboysbanner,
            title: "Bad Boys For Life",
            Description: "Miami detectives Mike Lowrey and Marcus Burnett must face off against a mother-and-son pair of drug lords who wreak vengeful havoc on their city.",
            Director: "Bilall Fallah",
            duration: '2h 4min',
            video: "https://www.youtube.com/watch?v=jKCj3XuPG8M",
            year: "2020",
            rated: "R",
            rating: 6,
            imdb: '6.5',
            rottenTomatoesRating: '75%',
            type: "movie",
            actors: ['Will Smith', 'Martin Lawrence'],
          },
          {
            id: 27,
            mainImage: birdsmain,
            bannerImage: birdsbanner,
            title: "Birds Of Prey",
            Description: "After splitting with the Joker, Harley Quinn joins superheroines Black Canary, Huntress, and Renee Montoya to save a young girl from an evil crime lord.",
            Director: "Cathy Yan",
            duration: '1h 49min',
            video: "https://www.youtube.com/watch?v=kGM4uYZzfu0",
            year: "2020",
            rated: "R",
            rating: 6,
            imdb: '6.1',
            rottenTomatoesRating: '79%',
            type: "movie",
            actors: ['Margot Robbie', 'Rosie Perez'],
          },
          {
            id: 28,
            mainImage: topgunmain,
            bannerImage: topgunbanner,
            title: "Top Gun: Maverick",
            Description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
            Director: "Joseph Kosinski",
            duration: '2h 10min',
            video: "https://www.youtube.com/watch?v=giXco2jaZ_4",
            year: "2022",
            rated: "PG-13",
            rating: 7,
            imdb: '8.2',
            rottenTomatoesRating: '96%',
            type: "movie",
            actors: ['Tom Cruise','Jennifer Connelly'],
          },
          {
            id: 29,
            mainImage: shangchimain,
            bannerImage: shangchibanner,
            title: "Shang-Chi and the Legend of the Ten Rings",
            Description: "Shang-Chi, the master of weaponry-based Kung Fu, is forced to confront his past after being drawn into the Ten Rings organization.",
            Director: "Destin Daniel Cretton",
            duration: '2h 12min',
            video: "https://www.youtube.com/watch?v=giWIr7U1deA",
            year: "2021",
            rated: "PG-13",
            rating: 8,
            imdb: '7.4',
            rottenTomatoesRating: '91%',
            type: "movie",
            actors: ['Simu Liu', 'Awkwafina'],
          },
          {
            id: 30,
            mainImage: creedmain,
            bannerImage: creedbanner,
            title: "Creed",
            Description: "The former World Heavyweight Champion Rocky Balboa serves as a trainer and mentor to Adonis Johnson, the son of his late friend and former rival Apollo Creed.",
            Director: "Ryan Coogler",
            duration: '2h 13min',
            video: "https://www.youtube.com/watch?v=Uv554B7YHk4",
            year: "2015",
            rated: "PG-13",
            rating: 6,
            imdb: '7.6',
            rottenTomatoesRating: '95%',
            type: "movie",
            actors: ['Micheal B Jordan', 'Sylvester Stallone'],
          },
          {
            id: 31,
            mainImage: martianmain,
            bannerImage: martianbanner,
            title: "The Martian",
            Description: "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive and can survive until a potential rescue.",
            Director: "Ridley",
            duration: '2h 24min',
            video: "https://www.youtube.com/watch?v=ej3ioOneTy8",
            year: "2015",
            rated: "PG-13",
            rating: 6,
            imdb: '8.0',
            rottenTomatoesRating: '91%',
            type: "movie",
            actors: ['Matt Damon', 'Jessica Chastain'],
          },
          {
            id: 32,
            mainImage: junglebookmain,
            bannerImage: junglebookbanner,
            title: "The Jungle Book",
            Description: "After a threat from the tiger Shere Khan forces him to flee the jungle, a man-cub named Mowgli embarks on a journey of self discovery with the help of panther Bagheera and free-spirited bear Baloo.",
            Director: "Jon Favreau",
            duration: '1h 46min',
            video: "https://www.youtube.com/watch?v=C4qgAaxB_pc",
            year: "2016",
            rated: "PG",
            rating: 6,
            imdb: '7.4',
            rottenTomatoesRating: '94%',
            type: "movie",
            actors: ['Neel Sethi', 'Bill Murray'],
          },
          {
            id: 33,
            mainImage: mandalorianmain,
            bannerImage: mandalorianbanner,
            title: "The Mandalorian",
            Description: "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
            Director: "Jon Favreau",
            duration: '3 Seasons 24 Episodes',
            video: "https://www.youtube.com/watch?v=Znsa4Deavgg",
            year: "2019-2023",
            rated: "TV-14",
            rating: 6,
            imdb: '8.6',
            rottenTomatoesRating: '90%',
            type: "tvseries",
            actors: ['Pedro Pascal', 'Chris Bartlett'],
          },
          {
            id: 34,
            mainImage: thirteenmain,
            bannerImage: thirteenbanner,
            title: "13 Reasons Why",
            Description: "Follows teenager Clay Jensen, in his quest to uncover the story behind his classmate and crush, Hannah, and her decision to end her life.",
            Director: "Tom McCarthy",
            duration: '4 Seasons 49 Episodes',
            video: "https://www.youtube.com/watch?v=poUq9ypynKs",
            year: "2017-2020",
            rated: "TV-MA",
            rating: 6,
            imdb: '7.5',
            rottenTomatoesRating: '35%',
            type: "tvseries",
            actors: ['Dylan Minnette', 'Katherine Langford'],
          },
          {
            id: 35,
            mainImage: jackryanmain,
            bannerImage: jackryanbanner,
            title: "Tom Clancy's Jack Ryan",
            Description: "Up-and-coming CIA analyst, Jack Ryan, is thrust into dangerous field assignments.",
            Director: "Phil Abraham",
            duration: '4 Seasons 20 Episodes',
            video: "https://www.youtube.com/watch?v=AK-Mdu1Epy0",
            year: "2018-2023",
            rated: "TV-MA",
            rating: 6,
            imdb: '8.0',
            rottenTomatoesRating: '78%',
            type: "tvseries",
            actors: ['John Krasinski','Wendell Pierce'],
          },
          {
            id: 36,
            mainImage: madmaxmain,
            bannerImage: madmaxbanner,
            title: "Mad Max: Fury Road",
            Description: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshipper and a drifter named Max.",
            Director: "George Miller",
            duration: '2h 0min',
            video: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
            year: "2015",
            rated: "R",
            rating: 6,
            imdb: '8.1',
            rottenTomatoesRating: '97%',
            type: "movie",
            actors: ['Tom Hardy', 'Charlize Theron'],
          },
          {
            id: 37,
            mainImage: transformermain,
            bannerImage: transformerbanner,
            title: "Transformer: Age Of Extinction",
            Description: "When humanity allies with a bounty hunter in pursuit of Optimus Prime, the Autobots turn to a mechanic and his family for help.",
            Director: "Michael Bay",
            duration: '2h 45min',
            video: "https://www.youtube.com/watch?v=T9bQCAWahLk",
            year: "2014",
            rated: "PG-13",
            rating: 6,
            imdb: '5.6',
            rottenTomatoesRating: '18%',
            type: "movie",
            actors: ['Mark Wahlberg', 'Nicola Peltz Beckham'],
          },
          {
            id: 38,
            mainImage: avengersmain,
            bannerImage: avengersbanner,
            title: "Avengers: Age of Ultron",
            Description: "When Tony Stark and Bruce Banner try to jump-start a dormant peacekeeping program called Ultron, things go horribly wrong and it's up to Earth's mightiest heroes to stop the villainous Ultron from enacting his terrible plan.",
            Director: "Joss Whedon",
            duration: '2h 21min',
            video: "https://www.youtube.com/watch?v=tmeOjFno6Do",
            year: "2015",
            rated: "PG-13",
            rating: 6,
            imdb: '7.3',
            rottenTomatoesRating: '76%',
            type: "movie",
            actors: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo'],
          },
          {
            id: 39,
            mainImage: parasitemain,
            bannerImage: parasitebanner,
            title: "Parasite",
            Description: "Greed and class discrimination threaten the newly-formed symbiotic relationship between the wealthy Park family and the destitute Kim clan",
            Director: "Bong Joon Ho",
            duration: '2h 12 min',
            video: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
            year: "2019",
            rated: "R",
            rating: 10,
            imdb: '8.5',
            rottenTomatoesRating: '99%',
            type: "movie",
            actors: ['Song Kang-ho', 'Lee Sun-kyun'],
          },
          {
            id: 40,
            mainImage: arrivalmain,
            bannerImage: arrivalbanner,
            title: "Arrival",
            Description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.",
            Director: "Denis Villeneuve",
            duration: '1h 46min',
            video: "https://www.youtube.com/watch?v=tFMo3UJ4B4g",
            year: "2016",
            rated: "PG-13",
            rating: 6,
            imdb: '7.9',
            rottenTomatoesRating: '94%',
            type: "movie",
            actors: ['Amy Adams','Jeremy Renner'],
          },
          {
            id: 41,
            mainImage: blademain,
            bannerImage: bladebanner,
            title: "Blade Runner: 2049",
            Description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
            Director: "Denis Villeneuve",
            duration: '2h 44min',
            video: "https://www.youtube.com/watch?v=gCcx85zbxz4",
            year: "2017",
            rated: "R",
            rating: 6,
            imdb: '8.0',
            rottenTomatoesRating: '88%',
            type: "movie",
            actors: ['Ryan Gosling', 'Ana de Armas'],
          },
          {
            id: 42,
            mainImage: mirzapurmain,
            bannerImage: mirzapurbanner,
            title: "Mirzapur",
            Description: "A shocking incident at a wedding procession ignites a series of events entangling the lives of two families in the lawless city of Mirzapur.",
            Director: "Karan Anshuman",
            duration: '3 Seasons 29 Episodes',
            video: "https://www.youtube.com/watch?v=33o3s4Vs4Sw",
            year: "2018-2023",
            rated: "TV-MA",
            rating: 6,
            imdb: '8.5',
            rottenTomatoesRating: '68%',
            type: "tvseries",
            actors: ['Ali Faizal','Rasika Dugal'],
          },
          {
            id: 43,
            mainImage: scaredmain,
            bannerImage: scaredbanner,
            title: "Scared Games",
            Description: "A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.",
            Director: "Neeraj Ghaywan",
            duration: '2 Seasns 16 Episodes',
            video: "https://www.youtube.com/watch?v=w-Xe8gLBc5I",
            year: "2018-2019",
            rated: "TV-MA",
            rating: 6,
            imdb: '8.6',
            rottenTomatoesRating: '71%',
            type: "tvseries",
            actors: ['Saif Ali Khan', 'Nawazuddin Siddiqui'],
          },
          {
            id: 44,
            mainImage: asurmain,
            bannerImage: asurbanner,
            title: "Asur",
            Description: "Shubh returns for revenge and this season he takes the challenge to a whole new level. With the heroes fallen apart, will a desolate Dhananjay Rajpoot and a torn Nikhil Nair be able to stop him?",
            Director: "Oni Sen",
            duration: '2 Seasons 16 Episodes',
            video: "https://www.youtube.com/watch?v=LDirQBvwx7g",
            year: "2020",
            rated: "TV-MA",
            rating: 6,
            imdb: '8.5',
            rottenTomatoesRating: '86%',
            type: "tvseries",
            actors: ['Arshad Warsi','Barun Sobti','Anupriya Goenka']
          },
          {
            id: 45,
            mainImage: Lvdmain,
            bannerImage: Lvdbanner,
            title: "Love, Death and Robots",
            Description: "A collection of animated short stories that span various genres including science fiction, fantasy, horror and comedy.",
            Director: "Tim Miller",
            duration: '3 Seasons 35 Episodes',
            video: "https://www.youtube.com/watch?v=Xj2b0swdpX8",
            year: "2019-2022",
            rated: "TV-MA",
            rating: 7,
            imdb: '8.4',
            rottenTomatoesRating: '86%',
            type: "tvseries",
            actors: ['Fred Tatasciore', 'Scott Whyte'],
          },
          {
            id: 46,
            mainImage: lucifermain,
            bannerImage: luciferbanner,
            title: "Lucifer",
            Description: "Lucifer Morningstar has decided he's had enough of being the dutiful servant in Hell and decides to spend some time on Earth to better understand humanity. He settles in Los Angeles - the City of Angels.",
            Director: "Nathan Hope",
            duration: '6 Seasons 93 Episodes',
            video: "https://www.youtube.com/watch?v=ueMwVGBwqRo",
            year: "2016-2021",
            rated: "TV-14",
            rating: 6,
            imdb: '8.1',
            rottenTomatoesRating: '87%',
            type: "tvseries",
            actors: ['Tom Ellis','Lauren German'],
          },
          {
            id: 47,
            mainImage: delhimain,
            bannerImage: delhibanner,
            title: "Delhi Crime",
            Description: "Based on the Nirbhaya case, Delhi Crime follows the Delhi Police investigation into the finding of the men who perpetrated this crime.",
            Director: "Richie Mehta",
            duration: '1 Season 7 Episodes',
            video: "https://www.youtube.com/watch?v=jNuKwlKJx2E",
            year: "2019",
            rated: "TV-MA",
            rating: 6,
            imdb: '8.5',
            rottenTomatoesRating: '88%',
            type: "tvseries",
            actors: ['Shefali Shah', 'Rasika Dugal'],
          },
          {
            id: 48,
            mainImage: blacksummermain,
            bannerImage: blacksummerbanner,
            title: "Black Summer",
            Description: "In the dark, early days of a zombie apocalypse, complete strangers band together to find the strength they need to survive and get back to loved ones.",
            Director: "John Hyams",
            duration: '2 Seasons 16 Episodes',
            video: "https://www.youtube.com/watch?v=O9-kJB8AVFA",
            year: "2019-2021",
            rated: "TV-MA",
            rating: 6,
            imdb: '6.6',
            rottenTomatoesRating: '87%',
            type: "tvseries",
            actors: ['Jamie King', 'Justin Chu Cary', 'Christine Lee'],
          },
          {
            id: 49,
            mainImage: sweetmain,
            bannerImage: sweetbanner,
            title: "Sweet Home",
            Description: "Hyun, a loner high school student who lost his entire family in a terrible accident, is forced to leave his home and has to face a new reality where monsters are trying to wipe out all of humanity.",
            Director: "Lee Eung-bok",
            duration: '3 Seasons 26 Episodes',
            video: "https://www.youtube.com/watch?v=vFg5YGAORhU",
            year: "2020-2024",
            rated: "TV-MA",
            rating: 6,
            imdb: '7.3',
            rottenTomatoesRating: '83%',
            type: "tvseries",
            actors: ['Song Kang', 'Lee Jin-wook'],
          },
          {
            id: 50,
            mainImage: Bloodhoundsmain,
            bannerImage: Bloodhoundsbanner,
            title: "Bloodhounds",
            Description: "In order to pay off their debt, three daring youths jump into the money-lending business while confronting the rich and powerful who prey on the weak.",
            Director: "Kim Joo-hwan",
            duration: '1 Season 8 Episodes',
            video: "https://www.youtube.com/watch?v=eyiR8pO50JE",
            year: "2023",
            rated: "TV-MA",
            rating: 9,
            imdb: '8.1',
            rottenTomatoesRating: '88%',
            type: "tvseries",
            actors: ['Woo Do-Hwan', 'Lee Sang-yi', 'Huh Joon-ho'],
          },
          {
            id: 51,
            mainImage: hellboundmain,
            bannerImage: hellboundbanner,
            title: "Hellbound",
            Description: "Unearthly beings deliver bloody condemnations, sending individuals to hell and giving rise to a religious group founded on the idea of divine justice.",
            Director: "Yeon Sang Ho",
            duration: '1 Season 8 Episodes',
            video: "https://www.youtube.com/watch?v=LtdXK6yNFN0",
            year: "2021",
            rated: "TV-MA",
            rating: 6,
            imdb: '6.6',
            rottenTomatoesRating: '97%',
            type: "tvseries",
            actors: ['Yoo Ah-in', 'Kim Hyn-joo'],
          },
          {
            id: 52,
            mainImage: Allmain,
            bannerImage: Allbanner,
            title: "All of us are dead",
            Description: "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out or turn into one of the rabid infected.",
            Director: "Lee Jae-kyoo",
            duration: '1 Season 13 Episodes',
            video: "https://www.youtube.com/watch?v=IN5TD4VRcSM",
            year: "2022",
            rated: "TV-MA",
            rating: 6,
            imdb: '7.5',
            rottenTomatoesRating: '89%',
            type: "tvseries",
            actors: ['Park Ji-hu', 'Yoon Chan-young', 'Cho Yi-hyun'],
          }
        ],
      }))
    },
  })